import React, { createContext, useContext, useState, ReactNode } from 'react'

export type Language = 'en' | 'fr' | 'he'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations object
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.projects': 'Projects',
    'nav.jobMatch': 'AI Match',
    'nav.experience': 'Experience',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.available': '👋 Available for new opportunities',
    'hero.greeting': 'Hi, I\'m',
    'hero.title': 'Software Engineer',
    'hero.subtitle': '& AI Specialist',
    'hero.description': 'Recent graduate with a passion for building innovative solutions that matter. Specialized in',
    'hero.ml': 'machine learning',
    'hero.web': 'web development',
    'hero.data': 'data analysis',
    'hero.viewWork': 'View My Work',
    'hero.downloadCV': 'Download CV',
    'hero.stat1': 'Projects Completed',
    'hero.stat2': 'Technologies Mastered',
    'hero.stat3': 'Graduate',
    
    // About Section
    'about.title': 'About',
    'about.me': 'Me',
    'about.subtitle': 'Passionate about technology and innovation',
    'about.description': 'Recent graduate in Software Engineering with AI specialization from Sami Shamoon College of Engineering. I combine technical expertise with creativity to develop innovative solutions.',
    'about.passion': 'My passion lies in creating applications that solve real problems and improve people\'s lives. I particularly enjoy working on AI/ML projects and modern web applications.',
    'about.collaboration': 'I believe in continuous learning and collaboration. Always ready to take on new challenges and contribute to exciting projects.',
    'about.education': 'Education',
    'about.degree': 'Computer Engineering / Software Engineering',
    'about.specialization': 'AI Specialization',
    'about.college': 'Sami Shamoon College of Engineering',
    'about.languages': 'Languages',
    'about.french': 'French',
    'about.english': 'English',
    'about.hebrew': 'Hebrew',
    'about.native': 'Native',
    'about.fluent': 'Fluent',
    'about.location': 'Location',
    'about.locationValue': 'Ashdod, Israel',
    'about.remoteWork': 'Open to remote and international opportunities',
    'about.experienceTitle': 'Experience',
    'about.experienceLevel': 'Graduate',
    'about.experienceDescription': 'Software development and project management',
    'about.availabilityTitle': 'Availability',
    'about.availabilityStatus': 'Immediate',
    'about.availabilityDescription': 'Ready for new challenges and opportunities',
    
    // Skills Section
    'skills.title': 'My',
    'skills.subtitle': 'Skills',
    'skills.description': 'Technologies and tools I work with',
    'skills.programming': 'Programming Languages',
    'skills.web': 'Web Development',
    'skills.database': 'Databases & Backend',
    'skills.tools': 'Tools & Technologies',
    'skills.testingQa': 'Testing & QA',
    'skills.professional': 'Professional Skills',
    'skills.problemSolving': 'Problem Solving',
    'skills.teamwork': 'Teamwork',
    'skills.communication': 'Communication',
    'skills.projectManagement': 'Project Management',
    'skills.adaptability': 'Adaptability',
    'skills.leadership': 'Leadership',
    'skills.testingDebugging': 'Testing & Debugging',
    'skills.agile': 'Agile / Scrum',
    
    // Projects Section
    'projects.title': 'My',
    'projects.subtitle': 'Projects',
    'projects.description': 'Some of my recent work and achievements',
    'projects.viewSource': 'View Source',
    'projects.liveDemo': 'Live Demo',
    'projects.liveDemoWindows': 'Live Demo for Windows',
    'projects.linkDesktopApp': 'Desktop app',
    'projects.linkSaaS': 'SaaS',
    'projects.downloadDesktopApp': 'Download desktop app',
    'projects.liveDemoSaaS': 'Live demo SaaS',
    'projects.features': 'Key Features:',

    // Job Match Section
    'jobMatch.badge': 'AI job matching',
    'jobMatch.title': 'Match a job with',
    'jobMatch.titleAccent': 'my profile',
    'jobMatch.subtitle': 'Paste a job post and get a quick, honest analysis of where my experience fits, which projects prove it, and what may be missing.',
    'jobMatch.inputTitle': 'Paste the job post',
    'jobMatch.inputHelp': 'The analysis runs locally first, then tries a free AI provider without an API key.',
    'jobMatch.placeholder': 'Paste the job description here...',
    'jobMatch.analyze': 'Analyze the job',
    'jobMatch.analyzing': 'Analyzing...',
    'jobMatch.example': 'Use example',
    'jobMatch.minLength': 'Add a little more detail for a useful analysis.',
    'jobMatch.emptyTitle': 'Ready to analyze',
    'jobMatch.emptyText': 'The result will show a score, relevant skills, matching projects and a final recommendation.',
    'jobMatch.errorTitle': 'There is a problem',
    'jobMatch.errorText': 'The AI analysis is temporarily unavailable. Please try again later.',
    'jobMatch.scoreLabel': 'Profile match',
    'jobMatch.aiPowered': 'AI analysis with Pollinations',
    'jobMatch.localPowered': 'Local analysis (AI provider busy)',
    'jobMatch.localNote': 'This result uses the portfolio matching engine while the free AI provider is unavailable.',
    'jobMatch.matchedSkills': 'Detected experience',
    'jobMatch.relevantProjects': 'Relevant projects',
    'jobMatch.strengths': 'Strong points',
    'jobMatch.gaps': 'Possible gaps',
    'jobMatch.tipsTitle': 'How to present better for this role',
    'jobMatch.none': 'No direct match detected yet.',
    'jobMatch.noProjects': 'No project is strongly connected to this job post yet.',
    'jobMatch.noMajorGaps': 'No major gap detected from the available text.',
    'jobMatch.verdict.strong': 'Very strong match',
    'jobMatch.verdict.good': 'Good match',
    'jobMatch.verdict.partial': 'Partial match',
    'jobMatch.verdict.low': 'Weak match',
    'jobMatch.recommendation.yes': 'Yes, strong fit',
    'jobMatch.recommendation.maybe': 'Maybe, worth discussing',
    'jobMatch.recommendation.no': 'Not the best fit',
    'jobMatch.summary.strong': 'This role aligns very well with my current experience and project portfolio.',
    'jobMatch.summary.good': 'This role has a solid overlap with my skills, with a few points to clarify.',
    'jobMatch.summary.partial': 'There is some relevant experience, but the role may require skills not strongly shown yet.',
    'jobMatch.summary.low': 'This job post does not strongly match the experience presented in this portfolio.',
    
    // Project Details
    'project.sportivis.title': 'Sportivis - Workout Tracker',
    'project.sportivis.description': 'Web app for tracking workouts and training programs (gym machines, free weights, cardio), with exercise library, live sessions, optional Supabase sync and AI-assisted program generation.',
    'project.sportivis.period': '2026',
    'project.sportivis.feature1': 'Filterable exercise library and structured training programs',
    'project.sportivis.feature2': 'Live workout flow with effort, rest and next-exercise sequencing',
    'project.sportivis.feature3': 'AI program generation and meal calorie estimates (Groq)',
    'project.sportivis.feature4': 'French/Hebrew UI with optional cloud sync via Supabase',

    'project.lionvault.title': 'The Lion Vault - Luxury Raffle Platform',
    'project.lionvault.description': 'Exclusive raffle platform for luxury items (watches, jewelry, rare objects) with public catalog, ticket purchases via Stripe, user dashboard and admin lot management.',
    'project.lionvault.period': '2026',
    'project.lionvault.feature1': 'Public catalog of lots with draw dates and entry prices',
    'project.lionvault.feature2': 'Authentication, Stripe Checkout and user participation history',
    'project.lionvault.feature3': 'Admin panel to create lots, upload photos, close and archive raffles',
    'project.lionvault.feature4': 'Per-lot admin view with buyers, ticket numbers and revenue',

    'project.surveyflow.title': 'SurveyFlow - Survey Platform',
    'project.surveyflow.description': 'Development of a comprehensive online platform allowing users to create, share and analyze static or dynamic surveys intuitively.',
    'project.surveyflow.period': '2024-2025',
    'project.surveyflow.feature1': 'Intuitive drag-and-drop survey builder',
    'project.surveyflow.feature2': 'Real-time analytics and reporting',
    'project.surveyflow.feature3': 'Multi-language support',
    'project.surveyflow.feature4': 'Advanced question types and logic',
    
    'project.sidour.title': 'SIDOUR AVODA - Schedule Manager',
    'project.sidour.description': 'Innovative desktop application and SaaS web application to optimize and manage work schedules in security environments. The web app includes a worker menu, a director menu, role management for sites, and support for complex sites.',
    'project.sidour.period': '2025',
    'project.sidour.usedBy': 'Used by Chevron / G-One',
    'project.sidour.feature1': 'Advanced scheduling algorithms',
    'project.sidour.feature2': 'Conflict detection and resolution',
    'project.sidour.feature3': 'Employee availability management',
    'project.sidour.feature4': 'Automated report generation',
    'project.sidour.feature5': 'Automatic update system from the application',
    'project.sidour.feature6': 'SaaS web application with worker & director menus',
    'project.sidour.feature7': 'Role management for sites',
    'project.sidour.feature8': 'Complex site support',
    
    'project.divespot.title': 'DIVESPOT - Social Network',
    'project.divespot.description': 'Social platform dedicated to diving enthusiasts, allowing them to share experiences, discover dive sites and connect with the community.',
    'project.divespot.period': '2024',
    'project.divespot.feature1': 'Interactive dive site mapping',
    'project.divespot.feature2': 'Community sharing and reviews',
    'project.divespot.feature3': 'Dive log management',
    'project.divespot.feature4': 'Real-time chat and messaging',
    
    'project.opetitsoins.title': 'Opetitsoins - Healthcare Website',
    'project.opetitsoins.description': 'Professional showcase website for a home healthcare service in Israel. Bilingual platform (French-Hebrew) offering comprehensive medical care services.',
    'project.opetitsoins.period': '2024',
    'project.opetitsoins.feature1': 'Responsive design with modern UI/UX',
    'project.opetitsoins.feature2': 'Bilingual support (French/Hebrew)',
    'project.opetitsoins.feature3': 'Service booking and contact forms',
    'project.opetitsoins.feature4': 'Professional healthcare presentation',
    
    'project.elsafitness.title': 'Elsa Fitness - Fitness Website',
    'project.elsafitness.description': 'Modern fitness website with course booking system and admin panel. Features a clean design for promoting fitness programs, personal training services, and includes a backend system for course management and reservations.',
    'project.elsafitness.period': '2024',
    'project.elsafitness.feature1': 'Modern and attractive design',
    'project.elsafitness.feature2': 'Course booking and reservation system',
    'project.elsafitness.feature3': 'Admin panel for course creation and management',
    'project.elsafitness.feature4': 'Responsive layout for all devices',
    
    'project.talavidan.title': 'Tal Avidan Website - Professional Runner',
    'project.talavidan.description': 'Professional website for Tal Avidan, a professional runner with over 12,000 followers on social media. Features modern design showcasing training programs and professional running services.',
    'project.talavidan.period': '2025',
    'project.talavidan.feature1': 'Modern and professional design',
    'project.talavidan.feature2': 'Responsive layout for all devices',
    'project.talavidan.feature3': 'Professional runner showcase',
    'project.talavidan.feature4': 'Social media integration',
    
    'project.tsahalhelp.title': 'Tsahal Help Organization - Suicide Prevention',
    'project.tsahalhelp.description': 'Website for a Tsahal soldiers support organization focused on suicide prevention and mental health support. Features resources, contact information, and support services for military personnel and their families.',
    'project.tsahalhelp.period': '2025',
    'project.tsahalhelp.feature1': 'Mental health resources and support',
    'project.tsahalhelp.feature2': 'Crisis intervention information',
    'project.tsahalhelp.feature3': 'Contact and support services',
    'project.tsahalhelp.feature4': 'Responsive design for accessibility',
    
    // Categories
    'category.showcaseWebsite': 'Website',
    'category.desktopWeb': 'Desktop & Web Application',
    
    // Experience Section
    'experience.title': 'My',
    'experience.subtitle': 'Background',
    'experience.description': 'My educational and professional journey',
    'experience.stat1': 'Graduate',
    'experience.stat2': 'Major Projects',
    'experience.stat3': 'Ready to Start',
    'experience.profileSummary': 'Profile Summary',
    'experience.freshGraduate': 'Fresh Graduate',
    'experience.peopleManaged': 'People Managed',
    'experience.majorProjects': 'Major Projects',
    'experience.readyToStart': 'Ready to Start',
    'experience.summary': 'Professional Summary',
    'experience.years': 'Years Experience',
    'experience.team': 'Team Size',
    'experience.dedication': 'Dedicated & Passionate',
    'experience.types.education': 'Education',
    'experience.types.freelance': 'Freelance',
    'experience.types.leadership': 'Leadership',
    'experience.types.technical': 'Technical Service',
    'experience.types.backend': 'Backend',
    'experience.location.israel': 'Israel',
    'experience.location.remote': 'Remote',
    'experience.teamSize': 'Team of 5 people',
    'experience.keyAchievements': 'Key Achievements',
    'experience.mainResponsibilities': 'Main Responsibilities',
    'experience.skillsDeveloped': 'Skills Developed',
    // Skills translations
    'skills.softwareDevelopment': 'Software Development',
    'skills.aiMl': 'AI/ML',
    'skills.fullStack': 'Full-Stack Development',
    'skills.teamManagement': 'Team Management',
    'skills.responsibility': 'Responsibility',
    'skills.webDevelopment': 'Web Development',
    'skills.clientManagement': 'Client Management',
    'skills.responsiveDesign': 'Responsive Design',
    'skills.userExperience': 'User Experience',
    'skills.technicalPrecision': 'Technical Precision',
    'skills.analyticalThinking': 'Analytical Thinking',
    'skills.attentionToDetail': 'Attention to Detail',
    'skills.diagnostics': 'Diagnostics',
    'skills.documentation': 'Documentation',
    
    // Experience Details
    'exp.education.title': 'Computer Engineering / Software Engineering',
    'exp.education.subtitle': 'AI Specialization',
    'exp.education.company': 'Sami Shamoon College of Engineering',
    'exp.education.period': '2022-2025',
    'exp.education.desc1': 'Comprehensive software engineering curriculum with AI focus',
    'exp.education.desc2': 'Specialized in machine learning and data analysis',
    'exp.education.desc3': 'Developed multiple full-stack applications',
    'exp.education.desc4': 'Strong foundation in algorithms and system design',
    'exp.education.desc5': 'Completed QA training and software quality coursework as part of the engineering curriculum',
    
    'exp.freelance.title': 'Web Developer',
    'exp.freelance.subtitle': 'Freelance',
    'exp.freelance.company': 'Freelance',
    'exp.freelance.period': '2024-2025',
    'exp.freelance.desc1': 'Development of modern web applications and websites',
    'exp.freelance.desc2': 'Full-stack development with React, TypeScript, and Node.js',
    'exp.freelance.desc3': 'Client project management and delivery with Git/GitHub workflows',
    'exp.freelance.desc4': 'Responsive design and user experience optimization',
    'exp.freelance.desc5': 'QA across freelance projects (2024-2025): manual testing, functional checks, regression, Postman/API validation and bug reporting',
    
    'exp.julius.title': 'Fullstack',
    'exp.julius.subtitle': 'Backend focus',
    'exp.julius.company': 'Julius Agency',
    'exp.julius.period': '2025 – Currently',
    'exp.julius.desc1': 'CRM project development and bug fixing. Specialized in backend development with TypeScript, Node.js, Flutter, JavaScript, Prisma and Supabase.',
    'exp.julius.desc2': 'Development of CRM features and modules',
    'exp.julius.desc3': 'Bug fixing, code quality improvement and Git/PR collaboration',
    'exp.julius.desc4': 'Backend architecture, API design and Agile/Jira delivery',
    'exp.julius.desc5': 'QA validation since 2025: issue reproduction, test scenarios, Postman/API checks and CRM workflow verification',
    
    'exp.security.title': 'Security Guard Manager',
    'exp.security.company': 'CHEVRON | G-ONE',
    'exp.security.period': '2024',
    'exp.security.desc1': 'Team leadership and coordination',
    'exp.security.desc2': 'Security protocol implementation',
    'exp.security.desc3': 'Incident reporting and management',
    'exp.security.desc4': 'Training and supervision of security personnel',
    
    'exp.military.title': 'Military Optic/Optronic Technician',
    'exp.military.company': 'TSAHAL (IDF)',
    'exp.military.period': '2019-2021',
    'exp.military.desc1': 'Advanced technical equipment maintenance',
    'exp.military.desc2': 'Precision instrument calibration',
    'exp.military.desc3': 'Technical problem-solving under pressure',
    'exp.military.desc4': 'Team collaboration in critical environments',
    
    // Contact Section
    'contact.title': 'Contact',
    'contact.me': 'Me',
    'contact.subtitle': 'Ready to collaborate? Don\'t hesitate to reach out to discuss your projects',
    'contact.info': 'Contact Information',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.social': 'Social Networks',
    'contact.availability': 'Availability',
    'contact.available': 'Available for new projects',
    'contact.availableDesc': 'I\'m currently looking for exciting opportunities in software development, AI/ML, or project management. Contact me to discuss!',
    'contact.downloadCV': 'Download My CV',
    'contact.form.title': 'Send Me a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sendEmail': 'Send by Email',
    'contact.form.sendWhatsApp': 'Send by WhatsApp',
    'contact.form.chooseMethod': 'Choose your sending method:',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subjectPlaceholder': 'Subject of your message',
    'contact.form.messagePlaceholder': 'Your message...',
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.skills': 'Compétences',
    'nav.projects': 'Projets',
    'nav.jobMatch': 'IA Matching',
    'nav.experience': 'Expérience',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.available': '👋 Disponible pour de nouvelles opportunités',
    'hero.greeting': 'Salut, je suis',
    'hero.title': 'Ingénieur Logiciel',
    'hero.subtitle': '& Spécialiste IA',
    'hero.description': 'Récent diplômé passionné par la création de solutions innovantes qui comptent. Spécialisé en',
    'hero.ml': 'apprentissage automatique',
    'hero.web': 'développement web',
    'hero.data': 'analyse de données',
    'hero.viewWork': 'Voir Mon Travail',
    'hero.downloadCV': 'Télécharger CV',
    'hero.stat1': 'Projets Terminés',
    'hero.stat2': 'Technologies Maîtrisées',
    'hero.stat3': 'Diplômé',
    
    // About Section
    'about.title': 'À propos',
    'about.me': 'de Moi',
    'about.subtitle': 'Passionné par la technologie et l\'innovation',
    'about.description': 'Récent diplômé en Génie Logiciel avec spécialisation IA du Collège d\'Ingénierie Sami Shamoon. Je combine expertise technique et créativité pour développer des solutions innovantes.',
    'about.passion': 'Ma passion réside dans la création d\'applications qui résolvent de vrais problèmes et améliorent la vie des gens. J\'aime particulièrement travailler sur des projets IA/ML et des applications web modernes.',
    'about.collaboration': 'Je crois en l\'apprentissage continu et la collaboration. Toujours prêt à relever de nouveaux défis et contribuer à des projets passionnants.',
    'about.education': 'Formation',
    'about.degree': 'Ingénieur Informatique / Génie Logiciel',
    'about.specialization': 'Spécialisation IA',
    'about.college': 'Collège d\'Ingénierie Sami Shamoon',
    'about.languages': 'Langues',
    'about.french': 'Français',
    'about.english': 'Anglais',
    'about.hebrew': 'Hébreu',
    'about.native': 'Natif',
    'about.fluent': 'Courant',
    'about.location': 'Localisation',
    'about.locationValue': 'Ashdod, Israël',
    'about.remoteWork': 'Ouvert au travail à distance et aux opportunités internationales',
    'about.experienceTitle': 'Expérience',
    'about.experienceLevel': 'Diplômé',
    'about.experienceDescription': 'Développement logiciel et gestion de projet',
    'about.availabilityTitle': 'Disponibilité',
    'about.availabilityStatus': 'Immédiate',
    'about.availabilityDescription': 'Prêt pour de nouveaux défis et opportunités',
    
    // Skills Section
    'skills.title': 'Mes',
    'skills.subtitle': 'Compétences',
    'skills.description': 'Technologies et outils avec lesquels je travaille',
    'skills.programming': 'Langages de Programmation',
    'skills.web': 'Développement Web',
    'skills.database': 'Bases de Données & Backend',
    'skills.tools': 'Outils & Technologies',
    'skills.testingQa': 'Tests & QA',
    'skills.professional': 'Compétences Professionnelles',
    'skills.problemSolving': 'Résolution de Problèmes',
    'skills.teamwork': 'Travail d\'Équipe',
    'skills.communication': 'Communication',
    'skills.projectManagement': 'Gestion de Projet',
    'skills.adaptability': 'Adaptabilité',
    'skills.leadership': 'Leadership',
    'skills.testingDebugging': 'Tests & Débogage',
    'skills.agile': 'Agile / Scrum',
    
    // Projects Section
    'projects.title': 'Mes',
    'projects.subtitle': 'Projets',
    'projects.description': 'Quelques-uns de mes travaux récents et réalisations',
    'projects.viewSource': 'Voir le Code',
    'projects.liveDemo': 'Démo Live',
    'projects.liveDemoWindows': 'Démo Live pour Windows',
    'projects.linkDesktopApp': 'Application bureau',
    'projects.linkSaaS': 'SaaS',
    'projects.downloadDesktopApp': 'Télécharger l\'application bureau',
    'projects.liveDemoSaaS': 'Démo live SaaS',
    'projects.features': 'Fonctionnalités Clés :',

    // Job Match Section
    'jobMatch.badge': 'Matching emploi avec IA',
    'jobMatch.title': 'Analyse une offre avec',
    'jobMatch.titleAccent': 'mon profil',
    'jobMatch.subtitle': 'Collez une offre d’emploi et obtenez une analyse rapide et honnête : où mon expérience correspond, quels projets le prouvent, et ce qui peut manquer.',
    'jobMatch.inputTitle': 'Collez l’offre',
    'jobMatch.inputHelp': 'L’analyse locale fonctionne toujours, puis un fournisseur IA gratuit sans clé enrichit la réponse si disponible.',
    'jobMatch.placeholder': 'Collez ici la description du poste...',
    'jobMatch.analyze': 'Analyser le poste',
    'jobMatch.analyzing': 'Analyse en cours...',
    'jobMatch.example': 'Utiliser un exemple',
    'jobMatch.minLength': 'Ajoutez un peu plus de détails pour une analyse utile.',
    'jobMatch.emptyTitle': 'Prêt à analyser',
    'jobMatch.emptyText': 'Le résultat affichera un score, les compétences détectées, les projets pertinents et une recommandation finale.',
    'jobMatch.errorTitle': 'Il y a un problème',
    'jobMatch.errorText': 'L’analyse IA est temporairement indisponible. Réessayez plus tard.',
    'jobMatch.scoreLabel': 'Correspondance profil',
    'jobMatch.aiPowered': 'Analyse IA avec Pollinations',
    'jobMatch.localPowered': 'Analyse locale (IA temporairement saturée)',
    'jobMatch.localNote': 'Ce résultat utilise le moteur de matching du portfolio tant que le fournisseur IA gratuit est indisponible.',
    'jobMatch.matchedSkills': 'Expérience détectée',
    'jobMatch.relevantProjects': 'Projets pertinents',
    'jobMatch.strengths': 'Points forts',
    'jobMatch.gaps': 'Points à clarifier',
    'jobMatch.tipsTitle': 'Comment mieux te présenter pour ce poste',
    'jobMatch.none': 'Aucune correspondance directe détectée pour l’instant.',
    'jobMatch.noProjects': 'Aucun projet n’est fortement relié à cette offre pour l’instant.',
    'jobMatch.noMajorGaps': 'Aucun écart majeur détecté à partir du texte disponible.',
    'jobMatch.verdict.strong': 'Très bonne correspondance',
    'jobMatch.verdict.good': 'Bonne correspondance',
    'jobMatch.verdict.partial': 'Correspondance partielle',
    'jobMatch.verdict.low': 'Correspondance faible',
    'jobMatch.recommendation.yes': 'Oui, très bon profil',
    'jobMatch.recommendation.maybe': 'Peut-être, à discuter',
    'jobMatch.recommendation.no': 'Pas le meilleur fit',
    'jobMatch.summary.strong': 'Ce poste correspond très bien à mon expérience actuelle et aux projets présentés.',
    'jobMatch.summary.good': 'Ce poste a une bonne base commune avec mes compétences, avec quelques points à clarifier.',
    'jobMatch.summary.partial': 'Il y a une expérience pertinente, mais le poste peut demander des compétences encore peu visibles ici.',
    'jobMatch.summary.low': 'Cette offre ne correspond pas fortement à l’expérience présentée dans ce portfolio.',
    
    // Project Details
    'project.sportivis.title': 'Sportivis - Suivi d\'entraînement',
    'project.sportivis.description': 'Application web de suivi de séances et programmes de sport (machines, poids libres, cardio), avec bibliothèque d\'exercices, séances live, sync Supabase optionnelle et génération de programmes par IA.',
    'project.sportivis.period': '2026',
    'project.sportivis.feature1': 'Bibliothèque d\'exercices filtrable et programmes structurés',
    'project.sportivis.feature2': 'Séance live avec enchaînement effort, repos et exercice suivant',
    'project.sportivis.feature3': 'Génération de programmes IA et estimation calorique des repas (Groq)',
    'project.sportivis.feature4': 'Interface FR/HE avec synchronisation cloud optionnelle via Supabase',

    'project.lionvault.title': 'The Lion Vault - Tombolas de luxe',
    'project.lionvault.description': 'Plateforme de tombolas exclusives pour pièces de luxe (montres, bijoux, objets rares) avec catalogue public, achat de tickets Stripe, espace utilisateur et administration des lots.',
    'project.lionvault.period': '2026',
    'project.lionvault.feature1': 'Catalogue public des lots avec date de tirage et prix',
    'project.lionvault.feature2': 'Authentification, Stripe Checkout et historique des participations',
    'project.lionvault.feature3': 'Admin : création de lots, photos, clôture et archivage',
    'project.lionvault.feature4': 'Vue admin par lot : acheteurs, numéros de tickets et montant encaissé',

    'project.surveyflow.title': 'SurveyFlow - Plateforme de Sondages',
    'project.surveyflow.description': 'Développement d\'une plateforme en ligne complète permettant aux utilisateurs de créer, partager et analyser des sondages statiques ou dynamiques de manière intuitive.',
    'project.surveyflow.period': '2024-2025',
    'project.surveyflow.feature1': 'Constructeur de sondages intuitif par glisser-déposer',
    'project.surveyflow.feature2': 'Analyses et rapports en temps réel',
    'project.surveyflow.feature3': 'Support multi-langues',
    'project.surveyflow.feature4': 'Types de questions avancés et logique',
    
    'project.sidour.title': 'SIDOUR AVODA - Gestionnaire d\'Horaires',
    'project.sidour.description': 'Application de bureau innovante conçue pour optimiser et gérer les horaires de travail dans les environnements de sécurité, avec des algorithmes d\'optimisation avancés.',
    'project.sidour.period': '2025',
    'project.sidour.feature1': 'Algorithmes de planification avancés',
    'project.sidour.feature2': 'Détection et résolution de conflits',
    'project.sidour.feature3': 'Gestion de la disponibilité des employés',
    'project.sidour.feature4': 'Génération automatique de rapports',
    'project.sidour.feature5': 'Système de mise à jour automatique depuis l\'application',
    
    'project.divespot.title': 'DIVESPOT - Réseau Social',
    'project.divespot.description': 'Plateforme sociale dédiée aux passionnés de plongée, leur permettant de partager des expériences, découvrir des sites de plongée et se connecter avec la communauté.',
    'project.divespot.period': '2024',
    'project.divespot.feature1': 'Cartographie interactive des sites de plongée',
    'project.divespot.feature2': 'Partage communautaire et avis',
    'project.divespot.feature3': 'Gestion du carnet de plongée',
    'project.divespot.feature4': 'Chat et messagerie en temps réel',
    
    'project.opetitsoins.title': 'Opetitsoins - Site de Santé',
    'project.opetitsoins.description': 'Site vitrine professionnel pour un service de soins à domicile en Israël. Plateforme bilingue (français-hébreu) offrant des services de soins médicaux complets.',
    'project.opetitsoins.period': '2024',
    'project.opetitsoins.feature1': 'Design responsive avec UI/UX moderne',
    'project.opetitsoins.feature2': 'Support bilingue (français/hébreu)',
    'project.opetitsoins.feature3': 'Formulaires de réservation et contact',
    'project.opetitsoins.feature4': 'Présentation professionnelle des soins',
    
    'project.elsafitness.title': 'Elsa Fitness - Site de Fitness',
    'project.elsafitness.description': 'Site de fitness moderne avec système de réservation de cours et panel d\'administration. Design épuré axé sur la promotion de programmes de fitness et services de coaching personnel, incluant un système backend pour la gestion des cours et réservations.',
    'project.elsafitness.period': '2024',
    'project.elsafitness.feature1': 'Design moderne et attractif',
    'project.elsafitness.feature2': 'Système de réservation de cours',
    'project.elsafitness.feature3': 'Panel d\'administration pour la création et gestion des cours',
    'project.elsafitness.feature4': 'Layout responsive pour tous appareils',
    
    'project.talavidan.title': 'Tal Avidan Website - Coureur Professionnel',
    'project.talavidan.description': 'Site professionnel pour Tal Avidan, coureur professionnel avec plus de 12 000 abonnés sur les réseaux sociaux. Design moderne présentant les programmes d\'entraînement et services de course professionnelle.',
    'project.talavidan.period': '2024',
    'project.talavidan.feature1': 'Design moderne et professionnel',
    'project.talavidan.feature2': 'Layout responsive pour tous appareils',
    'project.talavidan.feature3': 'Présentation du coureur professionnel',
    'project.talavidan.feature4': 'Intégration des réseaux sociaux',
    
    'project.tsahalhelp.title': 'Organisation d\'Aide Tsahal - Prévention du Suicide',
    'project.tsahalhelp.description': 'Site web pour une organisation de soutien aux soldats de Tsahal axée sur la prévention du suicide et le soutien en santé mentale. Propose des ressources, informations de contact et services de soutien pour le personnel militaire et leurs familles.',
    'project.tsahalhelp.period': '2024',
    'project.tsahalhelp.feature1': 'Ressources et soutien en santé mentale',
    'project.tsahalhelp.feature2': 'Informations d\'intervention de crise',
    'project.tsahalhelp.feature3': 'Services de contact et de soutien',
    'project.tsahalhelp.feature4': 'Design responsive pour l\'accessibilité',
    
    // Categories
    'category.showcaseWebsite': 'Site Web',
    'category.desktopWeb': 'Application bureau & Web',
    
    // Experience Section
    'experience.title': 'Mon',
    'experience.subtitle': 'Parcours',
    'experience.description': 'Mon parcours éducatif et professionnel',
    'experience.stat1': 'Diplômé',
    'experience.stat2': 'Projets Majeurs',
    'experience.stat3': 'Prêt à Commencer',
    'experience.profileSummary': 'Résumé de Profil',
    'experience.freshGraduate': 'Diplômé',
    'experience.peopleManaged': 'Personnes Gérées',
    'experience.majorProjects': 'Projets Majeurs',
    'experience.readyToStart': 'Prêt à Commencer',
    'experience.summary': 'Résumé Professionnel',
    'experience.years': 'Années d\'Expérience',
    'experience.team': 'Taille d\'Équipe',
    'experience.dedication': 'Dévoué & Passionné',
    'experience.types.education': 'Formation',
    'experience.types.freelance': 'Freelance',
    'experience.types.leadership': 'Leadership',
    'experience.types.technical': 'Service Technique',
    'experience.types.backend': 'Backend',
    'experience.location.israel': 'Israël',
    'experience.location.remote': 'À distance',
    'experience.teamSize': 'Équipe de 5 personnes',
    'experience.keyAchievements': 'Réalisations Clés',
    'experience.mainResponsibilities': 'Responsabilités Principales',
    'experience.skillsDeveloped': 'Compétences Développées',
    // Skills translations
    'skills.softwareDevelopment': 'Développement Logiciel',
    'skills.aiMl': 'IA/ML',
    'skills.fullStack': 'Développement Full-Stack',
    'skills.teamManagement': 'Gestion d\'Équipe',
    'skills.responsibility': 'Responsabilité',
    'skills.webDevelopment': 'Développement Web',
    'skills.clientManagement': 'Gestion Client',
    'skills.responsiveDesign': 'Design Responsive',
    'skills.userExperience': 'Expérience Utilisateur',
    'skills.technicalPrecision': 'Précision Technique',
    'skills.analyticalThinking': 'Pensée Analytique',
    'skills.attentionToDetail': 'Attention aux Détails',
    'skills.diagnostics': 'Diagnostics',
    'skills.documentation': 'Documentation',
    
    // Experience Details
    'exp.education.title': 'Ingénieur Informatique / Génie Logiciel',
    'exp.education.subtitle': 'Spécialisation IA',
    'exp.education.company': 'Collège d\'Ingénierie Sami Shamoon',
    'exp.education.period': '2022-2025',
    'exp.education.desc1': 'Cursus complet en génie logiciel avec focus IA',
    'exp.education.desc2': 'Spécialisé en apprentissage automatique et analyse de données',
    'exp.education.desc3': 'Développé plusieurs applications full-stack',
    'exp.education.desc4': 'Base solide en algorithmes et conception de systèmes',
    'exp.education.desc5': 'Formations QA complétées et cours de qualité logicielle dans le cursus d’ingénieur informatique',
    
    'exp.freelance.title': 'Développeur Web',
    'exp.freelance.subtitle': 'Freelance',
    'exp.freelance.company': 'Freelance',
    'exp.freelance.period': '2024-2025',
    'exp.freelance.desc1': 'Développement d\'applications web modernes et sites internet',
    'exp.freelance.desc2': 'Développement full-stack avec React, TypeScript et Node.js',
    'exp.freelance.desc3': 'Gestion de projets clients et livraison avec workflows Git/GitHub',
    'exp.freelance.desc4': 'Design responsive et optimisation de l\'expérience utilisateur',
    'exp.freelance.desc5': 'QA sur les projets freelance (2024-2025) : tests manuels, fonctionnels, régression, validation API/Postman et rapports de bugs',
    
    'exp.julius.title': 'Fullstack',
    'exp.julius.subtitle': 'Focus backend',
    'exp.julius.company': 'Julius Agency',
    'exp.julius.period': '2025 – Actuellement',
    'exp.julius.desc1': 'Développement de projet CRM et correction de bugs. Spécialisé en backend avec TypeScript, Node.js, Flutter, JavaScript, Prisma et Supabase.',
    'exp.julius.desc2': 'Développement de fonctionnalités et modules CRM',
    'exp.julius.desc3': 'Correction de bugs, qualité du code et collaboration Git/PR',
    'exp.julius.desc4': 'Architecture backend, conception d’API et livraison Agile/Jira',
    'exp.julius.desc5': 'Validation QA depuis 2025 : reproduction d’anomalies, scénarios de test, contrôles API/Postman et workflows CRM',
    
    'exp.security.title': 'Responsable Sécurité',
    'exp.security.company': 'CHEVRON | G-ONE',
    'exp.security.period': '2024',
    'exp.security.desc1': 'Leadership et coordination d\'équipe',
    'exp.security.desc2': 'Mise en œuvre des protocoles de sécurité',
    'exp.security.desc3': 'Rapport et gestion d\'incidents',
    'exp.security.desc4': 'Formation et supervision du personnel de sécurité',
    
    'exp.military.title': 'Technicien Optique/Optronique Militaire',
    'exp.military.company': 'TSAHAL (FDI)',
    'exp.military.period': '2019-2021',
    'exp.military.desc1': 'Maintenance d\'équipements techniques avancés',
    'exp.military.desc2': 'Calibration d\'instruments de précision',
    'exp.military.desc3': 'Résolution de problèmes techniques sous pression',
    'exp.military.desc4': 'Collaboration d\'équipe dans des environnements critiques',
    
    // Contact Section
    'contact.title': 'Me',
    'contact.me': 'Contacter',
    'contact.subtitle': 'Prêt à collaborer ? N\'hésitez pas à me contacter pour discuter de vos projets',
    'contact.info': 'Informations de Contact',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.location': 'Localisation',
    'contact.social': 'Réseaux Sociaux',
    'contact.availability': 'Disponibilité',
    'contact.available': 'Disponible pour de nouveaux projets',
    'contact.availableDesc': 'Je recherche actuellement des opportunités passionnantes en développement logiciel, IA/ML, ou gestion de projet. Contactez-moi pour en discuter !',
    'contact.downloadCV': 'Télécharger Mon CV',
    'contact.form.title': 'Envoyez-moi un Message',
    'contact.form.name': 'Nom Complet',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.send': 'Envoyer le Message',
    'contact.form.sendEmail': 'Envoyer par Email',
    'contact.form.sendWhatsApp': 'Envoyer par WhatsApp',
    'contact.form.chooseMethod': 'Choisissez votre méthode d\'envoi :',
    'contact.form.namePlaceholder': 'Votre nom',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.subjectPlaceholder': 'Sujet de votre message',
    'contact.form.messagePlaceholder': 'Votre message...',
  },
  
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.about': 'אודות',
    'nav.skills': 'כישורים',
    'nav.projects': 'פרויקטים',
    'nav.jobMatch': 'התאמת AI',
    'nav.experience': 'ניסיון',
    'nav.contact': 'צור קשר',
    
    // Hero Section
    'hero.available': '👋 זמין להזדמנויות חדשות',
    'hero.greeting': 'היי, אני',
    'hero.title': 'מהנדס תוכנה',
    'hero.subtitle': 'ומומחה בינה מלאכותית',
    'hero.description': 'בוגר טרי עם תשוקה לבניית פתרונות חדשניים שחשובים. מתמחה ב',
    'hero.ml': 'למידת מכונה',
    'hero.web': 'פיתוח אתרים',
    'hero.data': 'ניתוח נתונים',
    'hero.viewWork': 'צפה בעבודות שלי',
    'hero.downloadCV': 'הורד קורות חיים',
    'hero.stat1': 'פרויקטים שהושלמו',
    'hero.stat2': 'טכנולוגיות שנלמדו',
    'hero.stat3': 'בוגר',
    
    // About Section
    'about.title': 'אודות',
    'about.me': 'עליי',
    'about.subtitle': 'נלהב מטכנולוגיה וחדשנות',
    'about.description': 'בוגר טרי בהנדסת תוכנה עם התמחות בבינה מלאכותית ממכללת סמי שמעון להנדסה. אני משלב מומחיות טכנית עם יצירתיות לפיתוח פתרונות חדשניים.',
    'about.passion': 'התשוקה שלי טמונה ביצירת אפליקציות שפותרות בעיות אמיתיות ומשפרות את חיי האנשים. אני נהנה במיוחד לעבוד על פרויקטי בינה מלאכותית ואפליקציות אינטרנט מודרניות.',
    'about.collaboration': 'אני מאמין בלמידה מתמשכת ושיתוף פעולה. תמיד מוכן לקחת על עצמי אתגרים חדשים ולתרום לפרויקטים מרגשים.',
    'about.education': 'השכלה',
    'about.degree': 'תואר ראשון בהנדסת תוכנה',
    'about.specialization': 'התמחות בבינה מלאכותית',
    'about.college': 'מכללת סמי שמעון להנדסה',
    'about.languages': 'שפות',
    'about.french': 'צרפתית',
    'about.english': 'אנגלית',
    'about.hebrew': 'עברית',
    'about.native': 'שפת אם',
    'about.fluent': 'שוטף',
    'about.location': 'מיקום',
    'about.locationValue': 'אשדוד, ישראל',
    'about.remoteWork': 'פתוח לעבודה מרחוק והזדמנויות בינלאומיות',
    'about.experienceTitle': 'ניסיון',
    'about.experienceLevel': 'בוגר',
    'about.experienceDescription': 'פיתוח תוכנה וניהול פרויקטים',
    'about.availabilityTitle': 'זמינות',
    'about.availabilityStatus': 'מיידית',
    'about.availabilityDescription': 'מוכן לאתגרים והזדמנויות חדשות',
    
    // Skills Section
    'skills.title': 'הכישורים',
    'skills.subtitle': 'שלי',
    'skills.description': 'טכנולוגיות וכלים שאני עובד איתם',
    'skills.programming': 'שפות תכנות',
    'skills.web': 'פיתוח אתרים',
    'skills.database': 'מסדי נתונים ושרתים',
    'skills.tools': 'כלים וטכנולוגיות',
    'skills.testingQa': 'בדיקות ו-QA',
    'skills.professional': 'כישורים מקצועיים',
    'skills.problemSolving': 'פתרון בעיות',
    'skills.teamwork': 'עבודת צוות',
    'skills.communication': 'תקשורת',
    'skills.projectManagement': 'ניהול פרויקטים',
    'skills.adaptability': 'הסתגלות',
    'skills.leadership': 'מנהיגות',
    'skills.testingDebugging': 'בדיקות ודיבוג',
    'skills.agile': 'Agile / Scrum',
    
    // Projects Section
    'projects.title': 'הפרויקטים',
    'projects.subtitle': 'שלי',
    'projects.description': 'כמה מהעבודות וההישגים האחרונים שלי',
    'projects.viewSource': 'צפה בקוד',
    'projects.liveDemo': 'דמו חי',
    'projects.liveDemoWindows': 'דמו חי עבור Windows',
    'projects.linkDesktopApp': 'אפליקציית שולחן עבודה',
    'projects.linkSaaS': 'SaaS',
    'projects.downloadDesktopApp': 'הורד אפליקציית שולחן עבודה',
    'projects.liveDemoSaaS': 'דמו חי SaaS',
    'projects.features': 'תכונות מרכזיות:',

    // Job Match Section
    'jobMatch.badge': 'התאמת משרה עם AI',
    'jobMatch.title': 'נתח משרה מול',
    'jobMatch.titleAccent': 'הפרופיל שלי',
    'jobMatch.subtitle': 'הדביקו תיאור משרה וקבלו ניתוח מהיר והוגן של ההתאמה, הפרויקטים הרלוונטיים והפערים האפשריים.',
    'jobMatch.inputTitle': 'הדביקו את המשרה',
    'jobMatch.inputHelp': 'הניתוח המקומי תמיד עובד, ולאחר מכן ספק AI חינמי ללא מפתח מוסיף ניתוח אם הוא זמין.',
    'jobMatch.placeholder': 'הדביקו כאן את תיאור המשרה...',
    'jobMatch.analyze': 'נתח את המשרה',
    'jobMatch.analyzing': 'מנתח...',
    'jobMatch.example': 'השתמש בדוגמה',
    'jobMatch.minLength': 'הוסיפו עוד קצת פרטים כדי לקבל ניתוח שימושי.',
    'jobMatch.emptyTitle': 'מוכן לניתוח',
    'jobMatch.emptyText': 'התוצאה תציג ציון, כישורים שזוהו, פרויקטים רלוונטיים והמלצה סופית.',
    'jobMatch.errorTitle': 'יש בעיה',
    'jobMatch.errorText': 'ניתוח ה-AI אינו זמין כרגע. נסו שוב מאוחר יותר.',
    'jobMatch.scoreLabel': 'התאמת פרופיל',
    'jobMatch.aiPowered': 'ניתוח AI עם Pollinations',
    'jobMatch.localPowered': 'ניתוח מקומי (ספק ה-AI עמוס)',
    'jobMatch.localNote': 'התוצאה מבוססת על מנוע ההתאמה של הפורטפוליו כל עוד ספק ה-AI החינמי אינו זמין.',
    'jobMatch.matchedSkills': 'ניסיון שזוהה',
    'jobMatch.relevantProjects': 'פרויקטים רלוונטיים',
    'jobMatch.strengths': 'נקודות חוזק',
    'jobMatch.gaps': 'פערים אפשריים',
    'jobMatch.tipsTitle': 'איך להציג את הפרופיל טוב יותר למשרה הזו',
    'jobMatch.none': 'עדיין לא זוהתה התאמה ישירה.',
    'jobMatch.noProjects': 'עדיין אין פרויקט שמחובר חזק לתיאור המשרה הזה.',
    'jobMatch.noMajorGaps': 'לא זוהה פער משמעותי מהטקסט הזמין.',
    'jobMatch.verdict.strong': 'התאמה חזקה מאוד',
    'jobMatch.verdict.good': 'התאמה טובה',
    'jobMatch.verdict.partial': 'התאמה חלקית',
    'jobMatch.verdict.low': 'התאמה חלשה',
    'jobMatch.recommendation.yes': 'כן, התאמה חזקה',
    'jobMatch.recommendation.maybe': 'אולי, כדאי לבדוק',
    'jobMatch.recommendation.no': 'לא ההתאמה הטובה ביותר',
    'jobMatch.summary.strong': 'המשרה הזו מתאימה מאוד לניסיון ולפרויקטים שמוצגים בפרופיל.',
    'jobMatch.summary.good': 'יש התאמה טובה לכישורים שלי, עם כמה נקודות שכדאי לברר.',
    'jobMatch.summary.partial': 'יש ניסיון רלוונטי, אבל ייתכן שהמשרה דורשת כישורים שפחות מודגשים כאן.',
    'jobMatch.summary.low': 'תיאור המשרה לא מתאים בצורה חזקה לניסיון שמוצג בפורטפוליו.',
    
    // Project Details
    'project.sportivis.title': 'Sportivis - מעקב אימונים',
    'project.sportivis.description': 'אפליקציית ווב למעקב אחרי אימונים ותוכניות אימון (מכונות, משקולות חופשיות, קרדיו), עם ספריית תרגילים, אימונים חיים, סנכרון Supabase אופציונלי ויצירת תוכניות בעזרת AI.',
    'project.sportivis.period': '2026',
    'project.sportivis.feature1': 'ספריית תרגילים ניתנת לסינון ותוכניות אימון מובנות',
    'project.sportivis.feature2': 'אימון חי עם רצף מאמץ, מנוחה ותרגיל הבא',
    'project.sportivis.feature3': 'יצירת תוכניות AI והערכת קלוריות לארוחות (Groq)',
    'project.sportivis.feature4': 'ממשק FR/HE עם סנכרון ענן אופציונלי דרך Supabase',

    'project.lionvault.title': 'The Lion Vault - פלטפורמת הגרלות יוקרה',
    'project.lionvault.description': 'פלטפורמת הגרלות בלעדיות לפריטי יוקרה (שעונים, תכשיטים, חפצים נדירים) עם קטלוג ציבורי, רכישת כרטיסים ב-Stripe, אזור משתמש וניהול מנהל של מגרשים.',
    'project.lionvault.period': '2026',
    'project.lionvault.feature1': 'קטלוג ציבורי של מגרשים עם תאריכי הגרלה ומחירים',
    'project.lionvault.feature2': 'אימות, Stripe Checkout והיסטוריית השתתפויות',
    'project.lionvault.feature3': 'ניהול מנהל: יצירת מגרשים, תמונות, סגירה וארכוב',
    'project.lionvault.feature4': 'תצוגת מנהל לפי מגרש: קונים, מספרי כרטיסים והכנסות',

    'project.surveyflow.title': 'SurveyFlow - פלטפורמת סקרים',
    'project.surveyflow.description': 'פיתוח פלטפורמה מקוונת מקיפה המאפשרת למשתמשים ליצור, לשתף ולנתח סקרים סטטיים או דינמיים באופן אינטואיטיבי.',
    'project.surveyflow.period': '2024-2025',
    'project.surveyflow.feature1': 'בונה סקרים אינטואיטיבי בגרירה ושחרור',
    'project.surveyflow.feature2': 'ניתוח ודיווח בזמן אמת',
    'project.surveyflow.feature3': 'תמיכה בריבוי שפות',
    'project.surveyflow.feature4': 'סוגי שאלות מתקדמים ולוגיקה',
    
    'project.sidour.title': 'SIDOUR AVODA - מנהל משמרות',
    'project.sidour.description': 'אפליקציית שולחן עבודה ואפליקציית ווב SaaS לייעול וניהול לוחות זמנים בסביבות אבטחה. אפליקציית הווב כוללת תפריט עובד, תפריט מנהל, ניהול תפקידים לאתרים ותמיכה באתרים מורכבים.',
    'project.sidour.period': '2025',
    'project.sidour.usedBy': 'בשימוש אצל Chevron / G-One',
    'project.sidour.feature1': 'אלגוריתמי תכנון מתקדמים',
    'project.sidour.feature2': 'זיהוי ופתרון קונפליקטים',
    'project.sidour.feature3': 'ניהול זמינות עובדים',
    'project.sidour.feature4': 'יצירת דוחות אוטומטית',
    'project.sidour.feature5': 'מערכת עדכון אוטומטי מהאפליקציה',
    'project.sidour.feature6': 'אפליקציית ווב SaaS עם תפריטי עובד ומנהל',
    'project.sidour.feature7': 'ניהול תפקידים לאתרים',
    'project.sidour.feature8': 'תמיכה באתרים מורכבים',
    
    'project.divespot.title': 'DIVESPOT - רשת חברתית',
    'project.divespot.description': 'פלטפורמה חברתית המוקדשת לחובבי צלילה, המאפשרת להם לשתף חוויות, לגלות אתרי צלילה ולהתחבר עם הקהילה.',
    'project.divespot.period': '2024',
    'project.divespot.feature1': 'מיפוי אינטראקטיבי של אתרי צלילה',
    'project.divespot.feature2': 'שיתוף קהילתי וביקורות',
    'project.divespot.feature3': 'ניהול יומן צלילה',
    'project.divespot.feature4': 'צ\'אט והודעות בזמן אמת',
    
    'project.opetitsoins.title': 'Opetitsoins - אתר בריאות',
    'project.opetitsoins.description': 'אתר ויטרינה מקצועי לשירותי טיפול רפואי בבית בישראל. פלטפורמה דו-לשונית (צרפתית-עברית) המציעה שירותי טיפול רפואי מקיפים.',
    'project.opetitsoins.period': '2024',
    'project.opetitsoins.feature1': 'עיצוב רספונסיבי עם UI/UX מודרני',
    'project.opetitsoins.feature2': 'תמיכה דו-לשונית (צרפתית/עברית)',
    'project.opetitsoins.feature3': 'טפסי הזמנה ויצירת קשר',
    'project.opetitsoins.feature4': 'הצגה מקצועית של שירותי טיפול',
    
    'project.elsafitness.title': 'Elsa Fitness - אתר כושר',
    'project.elsafitness.description': 'אתר כושר מודרני עם מערכת הזמנת קורסים ופאנל ניהול. עיצוב נקי המתמקד בקידום תוכניות כושר ושירותי אימון אישי, כולל מערכת backend לניהול קורסים והזמנות.',
    'project.elsafitness.period': '2024',
    'project.elsafitness.feature1': 'עיצוב מודרני ומושך',
    'project.elsafitness.feature2': 'מערכת הזמנת קורסים',
    'project.elsafitness.feature3': 'פאנל ניהול ליצירה וניהול קורסים',
    'project.elsafitness.feature4': 'פריסה רספונסיבית לכל המכשירים',
    
    'project.talavidan.title': 'Tal Avidan Website - רץ מקצועי',
    'project.talavidan.description': 'אתר מקצועי לטל אבידן, רץ מקצועי עם יותר מ-12,000 עוקבים ברשתות החברתיות. עיצוב מודרני המציג תוכניות אימון ושירותי ריצה מקצועיים.',
    'project.talavidan.period': '2024',
    'project.talavidan.feature1': 'עיצוב מודרני ומקצועי',
    'project.talavidan.feature2': 'פריסה רספונסיבית לכל המכשירים',
    'project.talavidan.feature3': 'הצגת הרץ המקצועי',
    'project.talavidan.feature4': 'אינטגרציה עם רשתות חברתיות',
    
    'project.tsahalhelp.title': 'ארגון עזרה לצה"ל - מניעת התאבדות',
    'project.tsahalhelp.description': 'אתר לארגון תמיכה בחיילי צה"ל המתמקד במניעת התאבדות ותמיכה בבריאות הנפש. כולל משאבים, פרטי יצירת קשר ושירותי תמיכה לכוח אדם צבאי ולמשפחותיהם.',
    'project.tsahalhelp.period': '2024',
    'project.tsahalhelp.feature1': 'משאבים ותמיכה בבריאות הנפש',
    'project.tsahalhelp.feature2': 'מידע על התערבות במשבר',
    'project.tsahalhelp.feature3': 'שירותי יצירת קשר ותמיכה',
    'project.tsahalhelp.feature4': 'עיצוב רספונסיבי לנגישות',
    
    // Categories
    'category.showcaseWebsite': 'אתר אינטרנט',
    'category.desktopWeb': 'אפליקציית שולחן עבודה וווב',
    
    // Experience Section
    'experience.title': 'הרקע',
    'experience.subtitle': 'שלי',
    'experience.description': 'המסע החינוכי והמקצועי שלי',
    'experience.stat1': 'בוגר',
    'experience.stat2': 'פרויקטים מרכזיים',
    'experience.stat3': 'מוכן להתחיל',
    'experience.profileSummary': 'סיכום פרופיל מקצועי',
    'experience.freshGraduate': 'בוגר',
    'experience.peopleManaged': 'אנשים בניהול',
    'experience.majorProjects': 'פרויקטים מרכזיים',
    'experience.readyToStart': 'מוכן להתחיל',
    'experience.summary': 'סיכום מקצועי',
    'experience.years': 'שנות ניסיון',
    'experience.team': 'גודל צוות',
    'experience.dedication': 'מסור ונלהב',
    'experience.types.education': 'השכלה',
    'experience.types.freelance': 'פרילנס',
    'experience.types.leadership': 'מנהיגות',
    'experience.types.technical': 'שירות טכני',
    'experience.types.backend': 'בקאנד',
    'experience.location.israel': 'ישראל',
    'experience.location.remote': 'מרחוק',
    'experience.teamSize': 'צוות של 5 אנשים',
    'experience.keyAchievements': 'הישגים מרכזיים',
    'experience.mainResponsibilities': 'אחריות עיקרית',
    'experience.skillsDeveloped': 'כישורים שפותחו',
    // Skills translations
    'skills.softwareDevelopment': 'פיתוח תוכנה',
    'skills.aiMl': 'בינה מלאכותית/למידת מכונה',
    'skills.fullStack': 'פיתוח מלא',
    'skills.teamManagement': 'ניהול צוות',
    'skills.responsibility': 'אחריות',
    'skills.webDevelopment': 'פיתוח אתרים',
    'skills.clientManagement': 'ניהול לקוחות',
    'skills.responsiveDesign': 'עיצוב רספונסיבי',
    'skills.userExperience': 'חוויית משתמש',
    'skills.technicalPrecision': 'דיוק טכני',
    'skills.analyticalThinking': 'חשיבה אנליטית',
    'skills.attentionToDetail': 'קשב לפרטים',
    'skills.diagnostics': 'אבחון',
    'skills.documentation': 'תיעוד',
    
    // Experience Details
    'exp.education.title': 'תואר ראשון בהנדסת תוכנה',
    'exp.education.subtitle': 'התמחות בבינה מלאכותית',
    'exp.education.company': 'מכללת סמי שמעון להנדסה',
    'exp.education.period': '2022-2025',
    'exp.education.desc1': 'תכנית לימודים מקיפה בהנדסת תוכנה עם דגש על בינה מלאכותית',
    'exp.education.desc2': 'התמחות בלמידת מכונה וניתוח נתונים',
    'exp.education.desc3': 'פיתוח מספר אפליקציות full-stack',
    'exp.education.desc4': 'בסיס חזק באלגוריתמים ועיצוב מערכות',
    'exp.education.desc5': 'השלמת הכשרות QA וקורסים באיכות תוכנה במסגרת לימודי הנדסת תוכנה',
    
    'exp.freelance.title': 'מפתח אתרים',
    'exp.freelance.subtitle': 'פרילנס',
    'exp.freelance.company': 'פרילנס',
    'exp.freelance.period': '2024-2025',
    'exp.freelance.desc1': 'פיתוח אפליקציות אתרים מודרניות ואתרי אינטרנט',
    'exp.freelance.desc2': 'פיתוח full-stack עם React, TypeScript ו-Node.js',
    'exp.freelance.desc3': 'ניהול פרויקטי לקוחות ומסירה עם תהליכי Git/GitHub',
    'exp.freelance.desc4': 'עיצוב רספונסיבי ואופטימיזציה של חוויית המשתמש',
    'exp.freelance.desc5': 'QA בפרויקטי פרילנס (2024-2025): בדיקות ידניות, פונקציונליות, רגרסיה, אימות API/Postman ודיווח באגים',
    
    'exp.julius.title': 'Fullstack',
    'exp.julius.subtitle': 'התמחות בבקאנד',
    'exp.julius.company': 'Julius Agency',
    'exp.julius.period': '2025 – כיום',
    'exp.julius.desc1': 'פיתוח פרויקט CRM ותיקון באגים. מתמחה בפיתוח בקאנד עם TypeScript, Node.js, Flutter, JavaScript, Prisma ו-Supabase.',
    'exp.julius.desc2': 'פיתוח תכונות ומודולי CRM',
    'exp.julius.desc3': 'תיקון באגים, שיפור איכות קוד ושיתוף פעולה ב-Git/PR',
    'exp.julius.desc4': 'ארכיטקטורת בקאנד, עיצוב API ומסירה ב-Agile/Jira',
    'exp.julius.desc5': 'אימות QA מאז 2025: שחזור תקלות, תרחישי בדיקה, בדיקות API/Postman וזרימות CRM',
    
    'exp.security.title': 'מנהל אבטחה',
    'exp.security.company': 'CHEVRON | G-ONE',
    'exp.security.period': '2024',
    'exp.security.desc1': 'מנהיגות וקואורדינציה של צוות',
    'exp.security.desc2': 'יישום פרוטוקולי אבטחה',
    'exp.security.desc3': 'דיווח וניהול אירועים',
    'exp.security.desc4': 'הכשרה ופיקוח על צוות האבטחה',
    
    'exp.military.title': 'טכנאי אופטיקה/אופטרוניקה צבאי',
    'exp.military.company': 'צה"ל',
    'exp.military.period': '2019-2021',
    'exp.military.desc1': 'תחזוקת ציוד טכני מתקדם',
    'exp.military.desc2': 'כיול מכשירי דיוק',
    'exp.military.desc3': 'פתרון בעיות טכניות תחת לחץ',
    'exp.military.desc4': 'שיתוף פעולה בצוות בסביבות קריטיות',
    
    // Contact Section
    'contact.title': 'צור',
    'contact.me': 'קשר',
    'contact.subtitle': 'מוכן לשתף פעולה? אל תהסס לפנות אליי כדי לדון בפרויקטים שלך',
    'contact.info': 'פרטי קשר',
    'contact.email': 'אימייל',
    'contact.phone': 'טלפון',
    'contact.location': 'מיקום',
    'contact.social': 'רשתות חברתיות',
    'contact.availability': 'זמינות',
    'contact.available': 'זמין לפרויקטים חדשים',
    'contact.availableDesc': 'אני מחפש כרגע הזדמנויות מרגשות בפיתוח תוכנה, בינה מלאכותית/למידת מכונה, או ניהול פרויקטים. צור קשר לדיון!',
    'contact.downloadCV': 'הורד את קורות החיים שלי',
    'contact.form.title': 'שלח לי הודעה',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'אימייל',
    'contact.form.subject': 'נושא',
    'contact.form.message': 'הודעה',
    'contact.form.send': 'שלח הודעה',
    'contact.form.sendEmail': 'שלח באמצעות אימייל',
    'contact.form.sendWhatsApp': 'שלח באמצעות וואטסאפ',
    'contact.form.chooseMethod': 'בחר את שיטת השליחה שלך:',
    'contact.form.namePlaceholder': 'השם שלך',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subjectPlaceholder': 'נושא ההודעה שלך',
    'contact.form.messagePlaceholder': 'ההודעה שלך...',
  }
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string): string => {
    const translation = translations[language] as Record<string, string>
    return translation[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === 'he' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 